imports:
    - { resource: "@M2LUserBundle/Resources/config/security.yml" }

security:
    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN_LIGUE }

    role_hierarchy:
        ROLE_ADMIN_TENNIS:
            - ROLE_USER
            - ROLE_ADMIN_LIGUE
        ROLE_ADMIN_FOOT:
            - ROLE_USER
            - ROLE_ADMIN_LIGUE
        ROLE_ADMIN_LIGUE: ROLE_USER
        ROLE_ADMIN:
            - ROLE_ADMIN_LIGUE
            - ROLE_ALLOWED_TO_SWITCH