fos_user_security:
    resource: routing/security.yml
    prefix: /

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /compte

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /inscription

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /compte

m2_l_user_admin:
    path:     /admin/user
    defaults: { _controller: M2LUserBundle:Admin:admin }

m2_l_user_supprimer:
    path:     /supprimer/{id}
    defaults: { _controller: M2LUserBundle:Admin:supprimer }
    requirements:
        id: \d+